# syntax = docker/dockerfile:experimental

FROM python:3.12.3-slim-bookworm

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    git curl wget unzip build-essential libssl-dev libffi-dev \
    python3-dev python3-pip python3-setuptools python3-wheel
RUN rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache/pip pip3 install -U pip
RUN --mount=type=cache,target=/root/.cache/pip pip3 install MarkupSafe
RUN --mount=type=cache,target=/root/.cache/pip pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN --mount=type=cache,target=/root/.cache/pip pip3 install --force-reinstall transformers
# RUN --mount=type=cache,target=/root/.cache/pip pip3 install --force-reinstall typing-extensions

RUN python3 -c 'from transformers import CLIPModel, CLIPProcessor, CLIPTokenizer;CLIPModel.from_pretrained("openai/clip-vit-base-patch32");CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32");CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32");'
