# syntax = docker/dockerfile:experimental

FROM ceressorbonne/panoptic-clip-base:latest

COPY ../.. ./app/
WORKDIR ./app/panoptic_back/ 

RUN --mount=type=cache,target=/root/.cache/pip pip3 install -U pip
# RUN pip3 install --force-reinstall typing-extensions
RUN --mount=type=cache,target=/root/.cache/pip pip3 install --force-reinstall fastapi==0.99.1 fastapi-camelcase==1.0.5
RUN --mount=type=cache,target=/root/.cache/pip pip3 install .

RUN rm -rf /root/.cache/pip
RUN rm -rf /root/.cache/torch/hub/checkpoints

RUN mkdir -p /data/
RUN chown -R 1000:1000 /data/
RUN chmod -R 777 /data/

ENV PANOPTIC_HOST="0.0.0.0"
ENV IS_DOCKER="True"

EXPOSE 8000

CMD ["panoptic"]
